import { type ResourceId } from "./resources";
import type { Recipe } from "./types";

const bottle_fill_separate = <B extends ResourceId, F extends ResourceId>(
  bottle: B,
  fluid: F,
): Recipe[] => [
  {
    input: { [bottle]: 1, [fluid]: 1 },
    output: { [`${bottle} (${fluid})` as ResourceId]: 1 },
    duration: 2,
    machine: "Filling Unit",
  },
  {
    input: { [`${bottle} (${fluid})`]: 1 },
    output: { [bottle]: 1, [fluid]: 1 },
    duration: 2,
    machine: "Separating Unit",
  },
];

type FluidOf<T> = T extends `${string} (${infer G})` ? G : never;
type Fillable<B extends ResourceId> = FluidOf<
  Extract<ResourceId, `${B} (${string})`>
>;
const bottles = [
  "Amethyst Bottle",
  "Ferrium Bottle",
  "Cryston Bottle",
  "Steel Bottle",
  "Cuprium Bottle",
  "Hetonite Bottle",
] as const satisfies ResourceId[];
const liquids = [
  "Clean Water",
  "Precipitation Acid",
  "Sewage",
  "Jincao Solution",
  "Yazhen Solution",
  "Liquid Xiranite",
  "Liquid Heavy Xiranite",
  "Xircon Effluent",
  "Inert Xircon Effluent",
  "Cuprium Solution",
  "Hetonite Solution",
] as const satisfies Fillable<(typeof bottles)[number]>[];
const canisters = ["Cuprium Canister"] as const satisfies ResourceId[];
const gasses = [
  "Aquagen",
  "Acridgen",
  "Xiragen",
  "Heavy Xiragen",
  "Inergen",
  "Cuprium Gas",
  "Hetonite Gas",
  "Pyrrolite Gas",
] as const satisfies Fillable<(typeof canisters)[number]>[];

const liquid_recipes = bottles
  .map((bottle) =>
    liquids.map((liquid) => bottle_fill_separate(bottle, liquid)).flat(),
  )
  .flat();
const gas_recipes = canisters
  .map((canister) =>
    gasses.map((gas) => bottle_fill_separate(canister, gas)).flat(),
  )
  .flat();

export const recipe_list: Recipe[] = [
  {
    input: {},
    output: { "Clean Water": 1 },
    duration: 1,
    limit: { Wuling: "inf", Valley: 0 },
    machine: "Fluid Pump",
  },
  {
    input: {},
    output: { "Precipitation Acid": 1 },
    duration: 2,
    limit: { Wuling: "inf", Valley: 0 },
    machine: "Acid Resistant Pump Mk II",
  },
  {
    input: { "Buckflower Seed": 1 },
    output: { Buckflower: 1 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { "Citrome Seed": 1 },
    output: { Citrome: 1 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { "Aketine Seed": 1 },
    output: { Aketine: 1 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { "Sandleaf Seed": 1 },
    output: { Sandleaf: 1 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { "Yazhen Seed": 1, "Clean Water": 1 },
    output: { Yazhen: 2 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { "Jincao Seed": 1, "Clean Water": 1 },
    output: { Jincao: 2 },
    duration: 2,
    machine: "Planting Unit",
  },
  {
    input: { Buckflower: 1 },
    output: { "Buckflower Seed": 2 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Citrome: 1 },
    output: { "Citrome Seed": 2 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Sandleaf: 1 },
    output: { "Sandleaf Seed": 2 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Aketine: 1 },
    output: { "Aketine Seed": 2 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Yazhen: 1 },
    output: { "Yazhen Seed": 1 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Jincao: 1 },
    output: { "Jincao Seed": 1 },
    duration: 2,
    machine: "Seed-Picking Unit",
  },
  {
    input: { Ferrium: 1 },
    output: { "Ferrium Part": 1 },
    duration: 2,
    machine: "Fitting Unit",
  },
  {
    input: { "Amethyst Fiber": 1 },
    output: { "Amethyst Part": 1 },
    duration: 2,
    machine: "Fitting Unit",
  },
  {
    input: { Steel: 1 },
    output: { "Steel Part": 1 },
    duration: 2,
    machine: "Fitting Unit",
  },
  {
    input: { "Cryston Fiber": 1 },
    output: { "Cryston Part": 1 },
    duration: 2,
    machine: "Fitting Unit",
  },
  {
    input: { Cuprium: 1 },
    output: { "Cuprium Part": 1 },
    duration: 2,
    machine: "Fitting Unit",
  },
  {
    input: { Hetonite: 5 },
    output: { "Hetonite Part": 1 },
    duration: 10,
    machine: "Fitting Unit",
  },
  {
    input: { Pyrrolite: 5 },
    output: { "Pyrrolite Part": 1 },
    duration: 10,
    machine: "Fitting Unit",
  },
  {
    input: { Ferrium: 2 },
    output: { "Ferrium Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { "Amethyst Fiber": 2 },
    output: { "Amethyst Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { Steel: 2 },
    output: { "Steel Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { "Cryston Fiber": 2 },
    output: { "Cryston Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { Cuprium: 2 },
    output: { "Cuprium Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { Hetonite: 2 },
    output: { "Hetonite Bottle": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { Cuprium: 2, Inergen: 1 },
    output: { "Cuprium Canister": 1 },
    duration: 2,
    machine: "Moulding Unit",
  },
  {
    input: { "Ferrium Ore": 1 },
    output: { Ferrium: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Ferrium Powder": 1 },
    output: { Ferrium: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Amethyst Ore": 1 },
    output: { "Amethyst Fiber": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Amethyst Powder": 1 },
    output: { "Amethyst Fiber": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Originium Ore": 1 },
    output: { Origocrust: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Origocrust Powder": 1 },
    output: { Origocrust: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Dense Origocrust Powder": 1 },
    output: { "Packed Origocrust": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Dense Ferrium Powder": 1 },
    output: { Steel: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Cryston Powder": 1 },
    output: { "Cryston Fiber": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Dense Carbon Powder": 1 },
    output: { "Stabilized Carbon": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Dense Originium Powder": 1 },
    output: { "Dense Origocrust Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Originium Powder": 1 },
    output: { "Origocrust Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Yazhen: 1 },
    output: { Carbon: 2 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Jincao: 1 },
    output: { Carbon: 2 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Buckflower: 1 },
    output: { Carbon: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Citrome: 1 },
    output: { Carbon: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Sandleaf: 1 },
    output: { Carbon: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Yazhen Powder": 1 },
    output: { "Carbon Powder": 2 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Jincao Powder": 1 },
    output: { "Carbon Powder": 2 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Sandleaf Powder": 3 },
    output: { "Carbon Powder": 2 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Buckflower Powder": 1 },
    output: { "Carbon Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Citrome Powder": 1 },
    output: { "Carbon Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Ground Buckflower Powder": 1 },
    output: { "Dense Carbon Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Ground Citrome Powder": 1 },
    output: { "Dense Carbon Powder": 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { "Cuprium Ore": 1, "Clean Water": 1 },
    output: { Cuprium: 1, Sewage: 1 },
    duration: 2,
    machine: "Refining Unit",
  },
  {
    input: { Cuprium: 1 },
    output: { "Cuprium Powder": 1 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Ferrium: 1 },
    output: { "Ferrium Powder": 1 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { "Amethyst Fiber": 1 },
    output: { "Amethyst Powder": 1 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { "Originium Ore": 1 },
    output: { "Originium Powder": 1 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Carbon: 1 },
    output: { "Carbon Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Origocrust: 1 },
    output: { "Origocrust Powder": 1 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Buckflower: 1 },
    output: { "Buckflower Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Citrome: 1 },
    output: { "Citrome Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Sandleaf: 1 },
    output: { "Sandleaf Powder": 3 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Aketine: 1 },
    output: { "Aketine Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Jincao: 1 },
    output: { "Jincao Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Yazhen: 1 },
    output: { "Yazhen Powder": 2 },
    duration: 2,
    machine: "Shredding Unit",
  },
  {
    input: { Sewage: 1 },
    output: {},
    duration: 2,
    machine: "Water Treatment Unit",
  },
  {
    input: { "Xircon Effluent": 1 },
    output: {},
    duration: 2,
    machine: "Water Treatment Unit",
  },
  {
    input: { "Inert Xircon Effluent": 1 },
    output: {},
    duration: 2,
    machine: "Water Treatment Unit",
  },
  {
    input: { "Clean Water": 3 },
    output: {},
    duration: 1,
    machine: "Fluid Supply Unit",
  },
  {
    input: { "Precipitation Acid": 3 },
    output: {},
    duration: 1,
    machine: "Fluid Supply Unit",
  },

  {
    input: { "Clean Water": 1 },
    output: { Aquagen: 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { Aquagen: 1 },
    output: { "Clean Water": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { Acridgen: 1 },
    output: { "Precipitation Acid": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Precipitation Acid": 1 },
    output: { Acridgen: 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Liquid Xiranite": 1 },
    output: { Xiragen: 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { Xiragen: 1 },
    output: { "Liquid Xiranite": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Liquid Heavy Xiranite": 2 },
    output: { "Heavy Xiragen": 5 },
    duration: 10,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Heavy Xiragen": 5 },
    output: { "Liquid Heavy Xiranite": 2 },
    duration: 10,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Cuprium Gas": 1 },
    output: { "Cuprium Solution": 2 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Cuprium Solution": 2 },
    output: { "Cuprium Gas": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Hetonite Gas": 1 },
    output: { "Hetonite Solution": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },
  {
    input: { "Hetonite Solution": 1 },
    output: { "Hetonite Gas": 1 },
    duration: 2,
    machine: "Fluid-Gas Transmuting Unit",
  },

  {
    input: { "Hetonite Gas": 2, "Xiragen": 1 },
    output: { "Pyrrolite Gas": 1 },
    duration: 2,
    environment: "Acrid",
    machine: "Gas Reactor Globe",
  },

  {
    input: { "Ferrium Powder": 2, "Sandleaf Powder": 1 },
    output: { "Dense Ferrium Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Amethyst Powder": 2, "Sandleaf Powder": 1 },
    output: { "Cryston Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Originium Powder": 2, "Sandleaf Powder": 1 },
    output: { "Dense Originium Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Carbon Powder": 2, "Sandleaf Powder": 1 },
    output: { "Dense Carbon Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Origocrust Powder": 2, "Sandleaf Powder": 1 },
    output: { "Dense Origocrust Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Buckflower Powder": 2, "Sandleaf Powder": 1 },
    output: { "Ground Buckflower Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },
  {
    input: { "Citrome Powder": 2, "Sandleaf Powder": 1 },
    output: { "Ground Citrome Powder": 1 },
    duration: 2,
    machine: "Grinding Unit",
  },

  {
    input: { "Inert Xircon Effluent": 4 },
    output: { "Xircon Effluent": 1, "Clean Water": 1 },
    duration: 2,
    machine: "Purification Unit",
  },
  {
    input: { "Cuprium Solution": 4 },
    output: { "Hetonite Solution": 1, "Precipitation Acid": 1 },
    duration: 2,
    machine: "Purification Unit",
  },
  {
    input: { "Xiragen": 2, "Separator Core": 1 },
    output: { "Heavy Xiragen": 1 },
    duration: 2,
    environment: "Stable",
    machine: "Purification Unit",
  },
  {
    input: { "Cuprium Gas": 2, "Separator Core": 1 },
    output: { "Hetonite Gas": 2 },
    duration: 2,
    environment: "Stable",
    machine: "Purification Unit",
  },
  {
    input: { "Xiragen": 2, "Separator Core": 2 },
    output: { "Heavy Xiragen": 1 },
    duration: 2,
    machine: "Purification Unit",
  },
  {
    input: { "Cuprium Gas": 2, "Separator Core": 2 },
    output: { "Hetonite Gas": 2 },
    duration: 2,
    machine: "Purification Unit",
  },

  {
    input: { Xiragen: 1 },
    output: { Xiranite: 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { "Heavy Xiragen": 5 },
    output: { "Heavy Xiranite": 2 },
    duration: 10,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { "Cuprium Gas": 1 },
    output: { Cuprium: 2 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { "Hetonite Gas": 2 },
    output: { Hetonite: 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { "Pyrrolite Gas": 1 },
    output: { Pyrrolite: 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { Xiranite: 1 },
    output: { Xiragen: 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { "Heavy Xiranite": 2 },
    output: { "Heavy Xiragen": 5 },
    duration: 10,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { Cuprium: 2 },
    output: { "Cuprium Gas": 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { Hetonite: 1 },
    output: { "Hetonite Gas": 2 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },
  {
    input: { Pyrrolite: 1 },
    output: { "Pyrrolite Gas": 1 },
    duration: 2,
    machine: "Solid-Gas Transmuting Unit",
  },

  {
    input: { "Jincao Powder": 1, "Clean Water": 1 },
    output: { "Jincao Solution": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Yazhen Powder": 1, "Clean Water": 1 },
    output: { "Yazhen Solution": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Xiranite": 1, "Clean Water": 1 },
    output: { "Liquid Xiranite": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Heavy Xiranite": 1, "Precipitation Acid": 1 },
    output: { "Liquid Heavy Xiranite": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Cuprium Powder": 1, "Precipitation Acid": 1 },
    output: { "Cuprium Solution": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Liquid Xiranite": 1, "Sewage": 1 },
    output: { "Xircon Effluent": 1, "Inert Xircon Effluent": 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Xircon Effluent": 2, "Ferrium Powder": 1 },
    output: { Xircon: 1, Sewage: 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },
  {
    input: { "Hetonite Solution": 2, "Ferrium Powder": 1 },
    output: { Hetonite: 1, Sewage: 1 },
    duration: 2,
    machine: "Reactor Crucible",
  },

  {
    input: { "Amethyst Part": 5, "Aketine Powder": 1 },
    output: { "Industrial Explosive": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Amethyst Part": 5, "Originium Powder": 10 },
    output: { "LC Valley Battery": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Ferrium Part": 10, "Originium Powder": 15 },
    output: { "SC Valley Battery": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Steel Part": 10, "Dense Originium Powder": 15 },
    output: { "HC Valley Battery": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Ferrium Part": 10, "Ferrium Bottle (Yazhen Solution)": 5 },
    output: { "Yazhen Syringe [C]": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Cuprium Part": 10, "Cuprium Bottle (Yazhen Solution)": 5 },
    output: { "Yazhen Syringe [A]": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Ferrium Part": 10, "Ferrium Bottle (Jincao Solution)": 5 },
    output: { "Jincao Drink": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Cuprium Part": 10, "Cuprium Bottle (Jincao Solution)": 5 },
    output: { "Jincao Tea": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Xiranite": 5, "Dense Originium Powder": 15 },
    output: { "LC Wuling Battery": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Xircon": 5, "Dense Originium Powder": 20 },
    output: { "SC Wuling Battery": 1 },
    duration: 10,
    machine: "Packaging Unit",
  },
  {
    input: { "Cuprium Canister": 1, "Xiranite": 1 },
    output: { "Separator Core": 2 },
    duration: 2,
    machine: "Packaging Unit",
  },

  {
    input: { "Cuprium Bottle": 1, "Jincao Solution": 1 },
    output: { "Cuprium Bottle (Jincao Solution)": 1 },
    duration: 2,
    machine: "Filling Unit",
  },
  {
    input: { "Amethyst Bottle": 5, "Citrome Powder": 5 },
    output: { "Canned Citrome [C]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },
  {
    input: { "Ferrium Bottle": 10, "Citrome Powder": 10 },
    output: { "Canned Citrome [B]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },
  {
    input: { "Steel Bottle": 10, "Ground Citrome Powder": 10 },
    output: { "Canned Citrome [A]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },
  {
    input: { "Amethyst Bottle": 5, "Buckflower Powder": 5 },
    output: { "Buck Capsule [C]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },
  {
    input: { "Ferrium Bottle": 10, "Buckflower Powder": 10 },
    output: { "Buck Capsule [B]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },
  {
    input: { "Steel Bottle": 10, "Ground Buckflower Powder": 10 },
    output: { "Buck Capsule [A]": 1 },
    duration: 10,
    machine: "Filling Unit",
  },

  ...liquid_recipes,
  ...gas_recipes,

  {
    input: { "Carbon": 1, "Clean Water": 1 },
    output: { Xiranite: 1 },
    duration: 2,
    environment: "Stable",
    machine: "Forge of the Sky",
  },
  {
    input: { "Stabilized Carbon": 2, "Clean Water": 1 },
    output: { Xiranite: 1 },
    duration: 2,
    machine: "Forge of the Sky",
  },
  {
    input: { "Xiranite": 10, "Xircon Effluent": 5 },
    output: { "Heavy Xiranite": 1 },
    duration: 10,
    machine: "Forge of the Sky",
  },

  {
    input: { Sewage: 2 },
    output: {},
    duration: 1,
    machine: "Water Purifier",
  },
  {
    input: { Sewage: 30 },
    output: { "Xircon Effluent": 1 },
    duration: 15,
    machine: "Water Purifier",
  },

  {
    input: { "Originium Ore": 1 },
    output: { Power: 50 * 8 },
    duration: 8,
    machine: "Thermal Bank",
  },
  {
    input: { "LC Valley Battery": 1 },
    output: { Power: 220 * 40 },
    duration: 40,
    machine: "Thermal Bank",
  },
  {
    input: { "SC Valley Battery": 1 },
    output: { Power: 420 * 40 },
    duration: 40,
    machine: "Thermal Bank",
  },
  {
    input: { "HC Valley Battery": 1 },
    output: { Power: 1100 * 40 },
    duration: 40,
    machine: "Thermal Bank",
  },
  {
    input: { "LC Wuling Battery": 1 },
    output: { Power: 1600 * 40 },
    duration: 40,
    machine: "Thermal Bank",
  },
  {
    input: { "SC Wuling Battery": 1 },
    output: { Power: 3200 * 40 },
    duration: 40,
    machine: "Thermal Bank",
  },
  {
    input: {},
    output: { Power: 200 },
    duration: 1,
    machine: "Protocol Automation-Core",
  },

  {
    input: { "Origocrust": 5, "Amethyst Fiber": 5 },
    output: { "Amethyst Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { Origocrust: 10, Ferrium: 10 },
    output: { "Ferrium Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { "Packed Origocrust": 10, "Cryston Fiber": 10 },
    output: { "Cryston Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { "Hetonite Part": 2, "Heavy Xiranite": 2 },
    output: { "Hetonite Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { "Packed Origocrust": 10, "Xiranite": 10 },
    output: { "Xiranite Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { "Cuprium Part": 10, "Xiranite": 10 },
    output: { "Cuprium Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
  {
    input: { "Heavy Xiranite": 2, "Pyrrolite Part": 1 },
    output: { "Pyrrolite Component": 1 },
    duration: 10,
    machine: "Gearing Unit",
  },
];
