export const resource_list = {
  "Acridgen": { name: "酸性ガス", prevent_overflow: true },
  "Aketine Powder": { name: "アケトン粉末" },
  "Aketine Seed": { name: "アケトンの種" },
  "Aketine": { name: "アケトン樹木" },
  "Amethyst Bottle": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Clean Water)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Precipitation Acid)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Sewage)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Jincao Solution)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Yazhen Solution)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Liquid Xiranite)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Liquid Heavy Xiranite)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Xircon Effluent)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Inert Xircon Effluent)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Cuprium Solution)": { name: "紫晶製ボトル" },
  "Amethyst Bottle (Hetonite Solution)": { name: "紫晶製ボトル" },
  "Amethyst Component": { name: "紫晶装備部品" },
  "Amethyst Fiber": { name: "紫晶繊維" },
  "Amethyst Ore": { name: "紫晶鉱物" },
  "Amethyst Part": { name: "紫晶部品" },
  "Amethyst Powder": { name: "紫晶粉末" },
  "Aquagen": { name: "水蒸気", prevent_overflow: true },
  "Buck Capsule [A]": { name: "蕎花カプセルⅢ" },
  "Buck Capsule [B]": { name: "蕎花カプセルⅡ" },
  "Buck Capsule [C]": { name: "蕎花カプセルⅠ" },
  "Buckflower Powder": { name: "蕎花粉末" },
  "Buckflower Seed": { name: "蕎花の種" },
  "Buckflower": { name: "蕎花" },
  "Canned Citrome [A]": { name: "シトロームの缶詰Ⅲ" },
  "Canned Citrome [B]": { name: "シトロームの缶詰Ⅱ" },
  "Canned Citrome [C]": { name: "シトロームの缶詰Ⅰ" },
  "Carbon Powder": { name: "炭塊粉末" },
  "Carbon": { name: "炭塊" },
  "Citrome Powder": { name: "シトローム粉末" },
  "Citrome Seed": { name: "シトロームの種" },
  "Citrome": { name: "シトローム" },
  "Clean Water": { name: "水", prevent_overflow: true },
  "Cryston Bottle": { name: "高晶製ボトル" },
  "Cryston Bottle (Clean Water)": { name: "高晶製ボトル" },
  "Cryston Bottle (Precipitation Acid)": { name: "高晶製ボトル" },
  "Cryston Bottle (Sewage)": { name: "高晶製ボトル" },
  "Cryston Bottle (Jincao Solution)": { name: "高晶製ボトル" },
  "Cryston Bottle (Yazhen Solution)": { name: "高晶製ボトル" },
  "Cryston Bottle (Liquid Xiranite)": { name: "高晶製ボトル" },
  "Cryston Bottle (Liquid Heavy Xiranite)": { name: "高晶製ボトル" },
  "Cryston Bottle (Xircon Effluent)": { name: "高晶製ボトル" },
  "Cryston Bottle (Inert Xircon Effluent)": { name: "高晶製ボトル" },
  "Cryston Bottle (Cuprium Solution)": { name: "高晶製ボトル" },
  "Cryston Bottle (Hetonite Solution)": { name: "高晶製ボトル" },
  "Cryston Component": { name: "高晶装備部品" },
  "Cryston Fiber": { name: "高晶繊維" },
  "Cryston Part": { name: "高晶部品" },
  "Cryston Powder": { name: "高晶粉末" },
  "Cuprium Bottle": { name: "赤銅ボトル" },
  "Cuprium Bottle (Clean Water)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Precipitation Acid)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Sewage)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Jincao Solution)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Yazhen Solution)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Liquid Xiranite)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Liquid Heavy Xiranite)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Xircon Effluent)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Inert Xircon Effluent)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Cuprium Solution)": { name: "赤銅ボトル" },
  "Cuprium Bottle (Hetonite Solution)": { name: "赤銅ボトル" },
  "Cuprium Canister": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Aquagen)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Acridgen)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Xiragen)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Heavy Xiragen)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Inergen)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Cuprium Gas)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Hetonite Gas)": { name: "赤銅圧力タンク" },
  "Cuprium Canister (Pyrrolite Gas)": { name: "赤銅圧力タンク" },
  "Cuprium Component": { name: "赤銅装備部品" },
  "Cuprium Gas": { name: "赤銅ガス", prevent_overflow: true },
  "Cuprium Ore": { name: "赤銅鉱物" },
  "Cuprium Part": { name: "赤銅部品" },
  "Cuprium Powder": { name: "赤銅粉末" },
  "Cuprium Solution": { name: "赤銅溶液", prevent_overflow: true },
  "Cuprium": { name: "赤銅塊" },
  "Dense Carbon Powder": { name: "高密度炭塊粉末" },
  "Dense Ferrium Powder": { name: "高密度青鉄粉末" },
  "Dense Originium Powder": { name: "高密度源石粉末" },
  "Dense Origocrust Powder": { name: "高密度結晶粉末" },
  "Ferrium Bottle": { name: "青鉄製ボトル" },
  "Ferrium Bottle (Clean Water)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Precipitation Acid)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Sewage)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Jincao Solution)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Yazhen Solution)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Liquid Xiranite)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Liquid Heavy Xiranite)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Xircon Effluent)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Inert Xircon Effluent)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Cuprium Solution)": { name: "赤銅ボトル" },
  "Ferrium Bottle (Hetonite Solution)": { name: "赤銅ボトル" },
  "Ferrium Component": { name: "青鉄装備部品" },
  "Ferrium Ore": { name: "青鉄鉱物" },
  "Ferrium Part": { name: "鉄製部品" },
  "Ferrium Powder": { name: "青鉄粉末" },
  "Ferrium": { name: "青鉄塊" },
  "Ground Buckflower Powder": { name: "蕎花細粉" },
  "Ground Citrome Powder": { name: "シトローム細粉" },
  "HC Valley Battery": { name: "大容量谷地バッテリー" },
  "Heavy Xiragen": { name: "重息壌ガス", prevent_overflow: true },
  "Heavy Xiranite": { name: "重息壌" },
  "Hetonite Bottle": { name: "緋銅ボトル" },
  "Hetonite Bottle (Clean Water)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Precipitation Acid)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Sewage)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Jincao Solution)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Yazhen Solution)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Liquid Xiranite)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Liquid Heavy Xiranite)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Xircon Effluent)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Inert Xircon Effluent)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Cuprium Solution)": { name: "緋銅ボトル" },
  "Hetonite Bottle (Hetonite Solution)": { name: "緋銅ボトル" },
  "Hetonite Component": { name: "緋銅装備部品" },
  "Hetonite Gas": { name: "緋銅ガス", prevent_overflow: true },
  "Hetonite Part": { name: "緋銅部品" },
  "Hetonite Solution": { name: "緋銅溶液", prevent_overflow: true },
  "Hetonite": { name: "緋銅塊" },
  "Industrial Explosive": { name: "工業爆弾" },
  "Inergen": { name: "不活性ガス", prevent_overflow: true },
  "Inert Xircon Effluent": { name: "不活性壌晶廃液", prevent_overflow: true },
  "Jincao Drink": { name: "錦草ソーダⅠ" },
  "Jincao Powder": { name: "錦草粉末" },
  "Jincao Seed": { name: "錦草の種" },
  "Jincao Solution": { name: "錦草エキス", prevent_overflow: true },
  "Jincao Tea": { name: "錦草ソーダⅡ" },
  "Jincao": { name: "錦草" },
  "LC Valley Battery": { name: "小容量谷地バッテリー" },
  "LC Wuling Battery": { name: "小容量武陵バッテリー" },
  "Liquid Heavy Xiranite": { name: "液化重息壌", prevent_overflow: true },
  "Liquid Xiranite": { name: "液化息壌", prevent_overflow: true },
  "Originium Ore": { name: "源石鉱物" },
  "Originium Powder": { name: "源石粉末" },
  "Origocrust Powder": { name: "結晶外殻粉末" },
  "Origocrust": { name: "結晶外殻" },
  "Packed Origocrust": { name: "特製結晶" },
  "Power": { name: "電力" },
  "Precipitation Acid": { name: "沈殿酸", prevent_overflow: true },
  "Pyrrolite Component": { name: "焔銅装備部品" },
  "Pyrrolite Gas": { name: "焔銅ガス", prevent_overflow: true },
  "Pyrrolite Part": { name: "焔銅部品" },
  "Pyrrolite": { name: "焔銅塊" },
  "Sandleaf Powder": { name: "サンドリーフ粉末" },
  "Sandleaf Seed": { name: "サンドリーフの種" },
  "Sandleaf": { name: "サンドリーフ" },
  "SC Valley Battery": { name: "中容量谷地バッテリー" },
  "SC Wuling Battery": { name: "中容量武陵バッテリー" },
  "Separator Core": { name: "分離コア" },
  "Sewage": { name: "汚水", prevent_overflow: true },
  "Stabilized Carbon": { name: "安定炭塊" },
  "Steel Bottle": { name: "鋼製ボトル" },
  "Steel Bottle (Clean Water)": { name: "鋼製ボトル" },
  "Steel Bottle (Precipitation Acid)": { name: "鋼製ボトル" },
  "Steel Bottle (Sewage)": { name: "鋼製ボトル" },
  "Steel Bottle (Jincao Solution)": { name: "鋼製ボトル" },
  "Steel Bottle (Yazhen Solution)": { name: "鋼製ボトル" },
  "Steel Bottle (Liquid Xiranite)": { name: "鋼製ボトル" },
  "Steel Bottle (Liquid Heavy Xiranite)": { name: "鋼製ボトル" },
  "Steel Bottle (Xircon Effluent)": { name: "鋼製ボトル" },
  "Steel Bottle (Inert Xircon Effluent)": { name: "鋼製ボトル" },
  "Steel Bottle (Cuprium Solution)": { name: "鋼製ボトル" },
  "Steel Bottle (Hetonite Solution)": { name: "鋼製ボトル" },
  "Steel Part": { name: "鋼製部品" },
  "Steel": { name: "鋼" },
  "Xiragen": { name: "息壌ガス", prevent_overflow: true },
  "Xiranite Component": { name: "息壌装備部品" },
  "Xiranite": { name: "息壌" },
  "Xircon Effluent": { name: "壌晶廃液", prevent_overflow: true },
  "Xircon": { name: "壌晶" },
  "Yazhen Powder": { name: "芽針粉末" },
  "Yazhen Seed": { name: "芽針の種" },
  "Yazhen Solution": { name: "芽針エキス", prevent_overflow: true },
  "Yazhen Syringe [A]": { name: "芽針注射剤Ⅱ" },
  "Yazhen Syringe [C]": { name: "芽針注射剤Ⅰ" },
  "Yazhen": { name: "芽針" },
} as const satisfies Record<
  string,
  { name: string; prevent_overflow?: boolean }
>;
export type ResourceId = keyof typeof resource_list;
export const resource_ids = Object.keys(resource_list) as ResourceId[];

export interface Group {
  [key: string]: ResourceId[] | Group;
}
export const resource_group: Group = {
  Power: ["Power"],
  Ores: ["Originium Ore", "Amethyst Ore", "Ferrium Ore", "Cuprium Ore"],
  Liquids: ["Clean Water", "Precipitation Acid"],
  Gasses: ["Inergen", "Xiragen"],
  Plants: ["Buckflower", "Citrome", "Aketine", "Sandleaf", "Yazhen", "Jincao"],
  Products: {
    Parts: [
      "Origocrust",
      "Amethyst Part",
      "Ferrium Part",
      "Steel Part",
      "Cryston Part",
      "Cuprium Part",
      "Hetonite Part",
      "Pyrrolite Part",
      "Xiranite",
      "Heavy Xiranite",
    ],
    Bottles: [
      "Amethyst Bottle",
      "Cryston Bottle",
      "Ferrium Bottle",
      "Steel Bottle",
      "Cuprium Bottle",
      "Hetonite Bottle",
      "Cuprium Canister",
    ],
    Components: [
      "Amethyst Component",
      "Ferrium Component",
      "Cryston Component",
      "Hetonite Component",
      "Xiranite Component",
      "Cuprium Component",
      "Pyrrolite Component",
    ],
    Medicines: [
      "Buck Capsule [C]",
      "Buck Capsule [B]",
      "Buck Capsule [A]",
      "Canned Citrome [C]",
      "Canned Citrome [B]",
      "Canned Citrome [A]",
      "Yazhen Syringe [C]",
      "Yazhen Syringe [A]",
      "Jincao Drink",
      "Jincao Tea",
    ],
    Batteries: [
      "Originium Ore",
      "LC Valley Battery",
      "SC Valley Battery",
      "HC Valley Battery",
      "LC Wuling Battery",
      "SC Wuling Battery",
    ],
    Miscs: ["Industrial Explosive"],
  },
  All: resource_ids.toSorted((a, b) =>
    resource_list[a].name.localeCompare(resource_list[b].name, "ja"),
  ),
} as const satisfies Group;
